#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

found=false
raspi_config="raspi-config"
cmdline_file='/boot/cmdline.txt'
resize2fs_one_file='/etc/init.d/resize2fs_once'

while read line
do
  result=$(echo $line | grep "${raspi_config}")
  if [ "$result" != "" ];then
      found=true
  fi
done < $cmdline_file

if  $found ;then
  echo 'cmdline.txt content found raspi-config'
else
  echo 'cmdline.txt content not found raspi-config, add init=\/usr\/lib\/raspi-config\/init_resize.sh to /boot/cmdline.txt'
  sed -i "s/rootwait/rootwait quiet init=\/usr\/lib\/raspi-config\/init_resize.sh/g" $cmdline_file
fi

echo 'create /etc/init.d/resize2fs_once file'
rm -rf $resize2fs_one_file
touch $resize2fs_one_file

cat <<EOT >> $resize2fs_one_file
#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "\$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    ROOT_DEV=\$(findmnt / -o source -n) &&
    resize2fs \$ROOT_DEV &&
    update-rc.d resize2fs_once remove &&
    rm /etc/init.d/resize2fs_once &&
    log_end_msg \$?
    ;;
  *)
    echo "Usage: \$0 start" >&2
    exit 3
    ;;
esac
EOT

echo '/etc/init.d/resize2fs_once file authenticate'
sudo chmod +x $resize2fs_one_file
sudo update-rc.d resize2fs_once defaults

echo 'finish'
